### ISSUE TITLE
Chaos Awakens Crash

### ISSUE THREAD

**Issue by SynergyDeveloper** [Chaos-Awakens-Mod-Team/ChaosAwakens#110]
[24Jan2024 16:13:07.766] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, {MINECRAFT_USERNAME}, --version, 1.16.5, --gameDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\Forge Modpack CCUP, --assetsDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\assets, --assetIndex, 1.16, --uuid, {MINECRAFT_UUID}, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[24Jan2024 16:13:07.769] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_382 by Azul Systems, Inc.
[24Jan2024 16:13:08.369] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[24Jan2024 16:13:08.416] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[24Jan2024 16:13:08.496] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: Version: 3.2.2 build 10
[24Jan2024 16:13:08.497] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	 OS: Windows 10 v10.0
[24Jan2024 16:13:08.497] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	JRE: 1.8.0_382 amd64
[24Jan2024 16:13:08.497] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	JVM: OpenJDK 64-Bit Server VM v25.382-b05 by Azul Systems, Inc.
[24Jan2024 16:13:08.505] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: Loading library (system): lwjgl
[24Jan2024 16:13:08.510] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	Loaded from java.library.path: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.16.5-1.16.5-36.2.39\lwjgl.dll
[24Jan2024 16:13:08.560] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: Loading library: jemalloc
[24Jan2024 16:13:08.563] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	Loaded from java.library.path: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.16.5-1.16.5-36.2.39\jemalloc.dll
[24Jan2024 16:13:08.571] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: MemoryUtil allocator: JEmallocAllocator
[24Jan2024 16:13:08.576] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: Loading library: glfw
[24Jan2024 16:13:08.578] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	Loaded from java.library.path: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.16.5-1.16.5-36.2.39\glfw.dll
[24Jan2024 16:13:08.946] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: Loading library (system): lwjgl_stb
[24Jan2024 16:13:08.949] [main/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	Loaded from java.library.path: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.16.5-1.16.5-36.2.39\lwjgl_stb.dll
[24Jan2024 16:13:09.023] [Thread-3/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: Loading library (system): lwjgl_opengl
[24Jan2024 16:13:09.026] [Thread-3/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	Loaded from java.library.path: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\natives\1.16.5-1.16.5-36.2.39\lwjgl_opengl.dll
[24Jan2024 16:13:09.029] [Thread-3/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: Loading library: opengl32
[24Jan2024 16:13:09.031] [Thread-3/INFO] [STDERR/]: [org.lwjgl.system.APIUtil:apiLog:75]: 	Loaded from system paths: C:\windows\SYSTEM32\opengl32.dll
[24Jan2024 16:13:10.136] [main/ERROR] [mixin/]: Mixin config chaosawakens.mixins.json does not specify "minVersion" property
[24Jan2024 16:13:10.139] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\Forge Modpack CCUP, --assetsDir, C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\meta\assets, --uuid, {MINECRAFT_UUID}, --username, {MINECRAFT_USERNAME}, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[24Jan2024 16:13:10.816] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[24Jan2024 16:13:10.817] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.core.impl.ThrowableProxy.formatExtendedStackTraceTo(Ljava/lang/StringBuilder;Ljava/util/List;Lorg/apache/logging/log4j/core/pattern/TextRenderer;Ljava/lang/String;Ljava/lang/String;)V
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.log.TransformingThrowablePatternConverter.generateEnhancedStackTrace(TransformingThrowablePatternConverter.java:87)
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraftforge.fml.CrashReportExtender.generateEnhancedStackTrace(CrashReportExtender.java:65)
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraftforge.fml.CrashReportExtender.generateEnhancedStackTrace(CrashReportExtender.java:55)
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_71498_d(CrashReport.java:119)
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_71502_e(CrashReport.java:135)
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:248)
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[24Jan2024 16:13:10.818] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 10 more

it does say

[main/ERROR] [mixin/]: Mixin config chaosawakens.mixins.json does not specify "minVersion" property

could it be the forge version im using?

**Comment by SynergyDeveloper** [comment]
To Anyone Else Having This issue, i fixed it by adding this to the Chaos Awakens mixin json, dont know why i didnt do this first i legit made a mod yesterday

	"minVersion":"[43)",

**Comment by RaveTr** [comment]
Next update (0.12) is a rewrite of the entire mod, so uhh, fixed
