### ISSUE TITLE
Lava Eel crash 1.16.5

### ISSUE THREAD

**Issue by NitroSwiftBlade-alt** [Chaos-Awakens-Mod-Team/ChaosAwakens#122]
The Lava Eel is causing a enity tick error and I cant be near lava in th Nether

-- Entity being ticked --
Details:
	Entity Type: chaosawakens:lava_eel (io.github.chaosawakens.common.entity.LavaEelEntity)
	Entity ID: 169
	Entity Name: Lava Eel
	Entity's Exact location: 11.50, 27.75, -873.51
	Entity's Block location: World: (11,27,-874), Chunk: (at 11,1,6 in 0,-55; contains blocks 0,0,-880 to 15,255,-865), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
	Entity's Momentum: 0.00, 0.04, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:APP:securitycraft.mixins.json:piston.WorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:betterweather.mixins.json:access.ServerWorldAccess,pl:mixin:APP:betterweather.mixins.json:server.world.MixinServerWorld,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}

**Comment by RaveTr** [comment]
Fixed in 0.12
