### ISSUE TITLE
Crash when using Royal Guardian

### ISSUE THREAD

**Issue by PGgamer2** [Chaos-Awakens-Mod-Team/ChaosAwakens#68]
Mod version: 0.10.0.1
Forge version: 36.2.34
Side: Dedicated Server
```
[14:34:57] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.entity.projectile.ProjectileHelper.func_221273_a(Lnet/minecraft/entity/Entity;Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/AxisAlignedBB;Ljava/util/function/Predicate;D)Lnet/minecraft/util/math/EntityRayTraceResult;
        at io.github.chaosawakens.common.items.extended.RoyalGuardianSwordItem.onEntitySwing(RoyalGuardianSwordItem.java:82) ~[chaosawakens:0.10.0.1] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeItemStack.onEntitySwing(IForgeItemStack.java:241) ~[forge:?] {re:computing_frames,re:classloading}
        at net.minecraft.entity.LivingEntity.func_226292_a_(LivingEntity.java:1544) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_184609_a(LivingEntity.java:1539) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_184609_a(ServerPlayerEntity.java:1311) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1125) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}
```

**Comment by PGgamer2** [comment]
Same thing happens with SlayerChainsawItem

**Comment by Blackout03** [comment]
What were you doing at the time when it crashed? What did you click in-game? Can you post the full crash log?

**Comment by PGgamer2** [comment]
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 15/06/22 14.34
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.projectile.ProjectileHelper.func_221273_a(Lnet/minecraft/entity/Entity;Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/vector/Vector3d;Lnet/minecraft/util/math/AxisAlignedBB;Ljava/util/function/Predicate;D)Lnet/minecraft/util/math/EntityRayTraceResult;
	at io.github.chaosawakens.common.items.extended.RoyalGuardianSwordItem.onEntitySwing(RoyalGuardianSwordItem.java:82) ~[chaosawakens:0.10.0.1] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeItemStack.onEntitySwing(IForgeItemStack.java:241) ~[forge:?] {re:computing_frames,re:classloading}
	at net.minecraft.entity.LivingEntity.func_226292_a_(LivingEntity.java:1544) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_184609_a(LivingEntity.java:1539) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_184609_a(ServerPlayerEntity.java:1311) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1125) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 453019712 bytes (432 MB) / 3388473344 bytes (3231 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 1 total; -Xmx8G
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.25.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.25              |DONE      |Manifest: NOSIGNATURE
		darkcreatures-0.1.jar                             |Dark Creatures Mod            |darkcreatures                 |0.1                 |DONE      |Manifest: NOSIGNATURE
		mobbattle-1.16.5-2.3.8.2.jar                      |Mob Battle Mod                |mobbattle                     |1.16.5-2.3.8.2      |DONE      |Manifest: NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |DONE      |Manifest: NOSIGNATURE
		magnesium-1.5.jar                                 |Magnesium                     |magnesium                     |1.5                 |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		mce-0.1.jar                                       |More Customizable Explosives M|mce                           |0.1                 |DONE      |Manifest: NOSIGNATURE
		magnesium_extras-mc1.16.5_v1.3.1.jar              |Magnesium Extras              |magnesium_extras              |mc1.16.5_v1.3.1     |DONE      |Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.4.jar                    |AttributeFix                  |attributefix                  |10.1.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		chaosawakens-1.16.5-0.10.0.1.jar                  |Chaos Awakens                 |chaosawakens                  |0.10.0.1            |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		geckolib-forge-1.16.5-3.0.77.jar                  |GeckoLib                      |geckolib3                     |3.0.77              |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 12f72db4-02db-496a-8d0c-36052e14dab9
	Player Count: 3 / 20; [ServerPlayerEntity['PGgamer06'/198, l='ServerLevel[world]', x=64.35, y=67.13, z=60.49], ServerPlayerEntity['sasssogamer'/329, l='ServerLevel[world]', x=61.26, y=63.94, z=46.39], ServerPlayerEntity['Blocchino06'/2387, l='ServerLevel[world]', x=63.67, y=65.82, z=61.85]]
	Data Packs: vanilla, mod:mowziesmobs, mod:darkcreatures, mod:mobbattle (incompatible), mod:wyrmroost (incompatible), mod:magnesium, mod:ferritecore (incompatible), mod:mce, mod:magnesium_extras, mod:attributefix, mod:chaosawakens, mod:forge, mod:geckolib3 (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:iceandfire (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by PGgamer2** [comment]
The `getEntityHitResult(Entity p_221273_0_, Vector3d p_221273_1_, Vector3d p_221273_2_, AxisAlignedBB p_221273_3_, Predicate<Entity> p_221273_4_, double p_221273_5_)` method is client-only

The `getEntityHitResult(World p_221269_0_, Entity p_221269_1_, Vector3d p_221269_2_, Vector3d p_221269_3_, AxisAlignedBB p_221269_4_, Predicate<Entity> p_221269_5_)` method works on both sides so it could be a good replacement

**Comment by Blackout03** [comment]
Oh thanks for the info

**Comment by Blackout03** [comment]
Oh actually that doesn't have the double value at the end so idk

**Comment by Blackout03** [comment]
ok yep does fix it

**Comment by PGgamer2** [comment]
BTW if it's helpful I did a quick scan of the word getEntityHitResult in the project:

```
  chaosawakens\common\items\CAToolItem.java
	Line 78: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\AttitudeAdjusterItem.java
	Line  77: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\BattleAxeItem.java
	Line  81: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\BigBerthaItem.java
	Line  81: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\EnchantedScytheItem.java
	Line  75: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\QueenScaleBattleAxeItem.java
	Line  81: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\RoyalGuardianSwordItem.java
	Line  82: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\ScytheItem.java
	Line  73: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
  chaosawakens\common\items\extended\SlayerChainsawItem.java
	Line  97: EntityRayTraceResult result = ProjectileHelper.getEntityHitResult(entity, eyeVec, targetVec, bb, EntityPredicates.NO_CREATIVE_OR_SPECTATOR, reachSqr);
```
They should all cause the same issue

**Comment by Blackout03** [comment]
Update is out now btw. CAToolItem wasn't updated but it is an unused class so doesn't matter
