### ISSUE TITLE
Whale crash

### ISSUE THREAD

**Issue by Nuclear4Hurricane** [Chaos-Awakens-Mod-Team/ChaosAwakens#88]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/22/23 6:31 PM
Description: Ticking entity

java.lang.ArithmeticException: / by zero
	at io.github.chaosawakens.common.entity.WhaleEntity$WhaleBreatheGoal.func_75253_b(WhaleEntity.java:429) ~[?:0.11.0.1] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75253_b(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.func_220881_e(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$7740/1202022736.test(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chaosawakens.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at io.github.chaosawakens.common.entity.WhaleEntity.func_70636_d(WhaleEntity.java:142) ~[?:0.11.0.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chaosawakens.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at io.github.chaosawakens.common.entity.WhaleEntity.func_70071_h_(WhaleEntity.java:271) ~[?:0.11.0.1] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$7733/222282464.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$7355/658762165.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.chaosawakens.common.entity.WhaleEntity$WhaleBreatheGoal.func_75253_b(WhaleEntity.java:429) ~[?:0.11.0.1] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75253_b(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.func_220881_e(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$7740/1202022736.test(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2413) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chaosawakens.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at io.github.chaosawakens.common.entity.WhaleEntity.func_70636_d(WhaleEntity.java:142) ~[?:0.11.0.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chaosawakens.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at io.github.chaosawakens.common.entity.WhaleEntity.func_70071_h_(WhaleEntity.java:271) ~[?:0.11.0.1] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$7733/222282464.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: chaosawakens:whale (io.github.chaosawakens.common.entity.WhaleEntity)
	Entity ID: 15598
	Entity Name: Whale
	Entity's Exact location: 747.58, 61.36, -803.12
	Entity's Block location: World: (747,61,-804), Chunk: (at 11,3,12 in 46,-51; contains blocks 736,0,-816 to 751,255,-801), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
	Entity's Momentum: 0.00, 0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?] {re:mixin,re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['NuclearLord1'/353, l='ServerLevel[ChaosAwakens]', x=774.48, y=63.00, z=-800.56]]
	Chunk stats: ServerChunkCache: 3546
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,-160), Chunk: (at 0,4,0 in 0,-10; contains blocks 0,0,-160 to 15,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 44428 game time, 7283 day time
	Level name: ChaosAwakens
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 14566 (now: false), thunder time: 32635 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$7355/658762165.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6944380448 bytes (6622 MB) / 8321499136 bytes (7936 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=64M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		AttributeFix-1.16.5-10.1.4.jar                    |AttributeFix                  |attributefix                  |10.1.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		ProjectE-1.16.5-PE1.0.2.jar                       |ProjectE                      |projecte                      |PE1.0.2             |DONE      |Manifest: NOSIGNATURE
		chaosawakens-1.16.5-0.11.0.1.jar                  |Chaos Awakens                 |chaosawakens                  |0.11.0.1            |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 7dcb2512-e8d6-4ef0-a051-e0e91481c93d
	Player Count: 1 / 8; [ServerPlayerEntity['NuclearLord1'/353, l='ServerLevel[ChaosAwakens]', x=774.48, y=63.00, z=-800.56]]
	Data Packs: vanilla, mod:attributefix, mod:projecte, mod:chaosawakens, mod:forge, mod:geckolib3 (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by RaveTr** [comment]
Known issue, fixed for next update
