### ISSUE TITLE
Mixin config chaosawakens.mixins.json does not specify "minVersion" property

### ISSUE THREAD

**Issue by Qawtykit** [Chaos-Awakens-Mod-Team/ChaosAwakens#93]
i can't find anything on this problem
the april fools versions don't crash
Logs:

[21:31:52] [main/INFO]: ModLauncher running: args [--username, pewpewmachine09, --version, forge-36.2.34, --gameDir, C:\Users\joshu\curseforge\minecraft\Instances\Chaos Expanded, --assetsDir, C:\Users\joshu\curseforge\minecraft\Install\assets, --assetIndex, 1.16, --uuid, 7d95beb577624f27886f78b6535a4c0a, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.34, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[21:31:52] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_51 by Oracle Corporation
[21:31:52] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[21:31:54] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[21:31:54] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/joshu/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[21:32:00] [main/ERROR]: Mixin config chaosawakens.mixins.json does not specify "minVersion" property
[21:32:00] [main/ERROR]: Mixin config chaosadditions.mixins.json does not specify "minVersion" property
[21:32:00] [main/INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[21:32:00] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-36.2.34, --gameDir, C:\Users\joshu\curseforge\minecraft\Instances\Chaos Expanded, --assetsDir, C:\Users\joshu\curseforge\minecraft\Install\assets, --uuid, 7d95beb577624f27886f78b6535a4c0a, --username, pewpewmachine09, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[21:32:00] [main/INFO]: Loaded configuration file for Sodium: 90 options available, 1 override(s) found
[21:32:00] [main/WARN]: Reference map 'chaosadditions.refmap.json' for chaosadditions.mixins.json could not be read. If this is a development environment you can ignore this message
[21:32:04] [main/WARN]: Error loading class: dev/ftb/mods/ftbmoney/shop/ShopEntry (java.lang.ClassNotFoundException: null)
[21:32:04] [main/WARN]: @Mixin target dev.ftb.mods.ftbmoney.shop.ShopEntry was not found questsadditions.mixins.json:MixinFTBShop
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.goal.GoalSelectorMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.nearby_entity_tracking.LivingEntityMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.nearby_entity_tracking.ServerWorldMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.nearby_entity_tracking.WorldChunkMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.nearby_entity_tracking.WorldMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.nearby_entity_tracking.goals.FleeEntityGoalMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.nearby_entity_tracking.goals.LookAtGoalMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.pathing.ChunkCacheMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.pathing.LandPathNodeMakerMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.pathing.MixinAbstractBlockState' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.pathing.MixinBlock' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.pathing.PathNodeNavigatorMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.poi.PointOfInterestStorageMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.poi.PointOfInterestSetMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.poi.PointOfInterestTypeMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.poi.SerializingRegionBasedStorageMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.poi.fast_portals.PortalForcerMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.raid.PickupBannerAsLeaderGoalMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.raid.RaidMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.task.CompositeTaskMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.task.FindInteractionTargetTaskMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.task.RunModeMixin$RunOneMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.task.RunModeMixin$TryAllMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.task.TaskMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.task.WeightedListMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:04] [main/WARN]: Force-disabling mixin 'ai.task.TaskAccessorMixin' as rule 'mixin.ai' (added by user configuration) disables it and children
[21:32:05] [main/ERROR]: No rules matched mixin 'client.world.MixinClientWorld', treating as foreign and disabling!
[21:32:05] [main/WARN]: Disabling MixinClientWorld due to conflict with AbnormalsCore
[21:32:08] [pool-3-thread-1/FATAL]: Mixin apply failed expandability.mixins.json:swimming.LivingEntityMixin -> net.minecraft.entity.LivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/entity/LivingEntity::setInWater with priority 1000 cannot inject into net/minecraft/entity/LivingEntity::func_213352_e(Lnet/minecraft/util/math/vector/Vector3d;)V merged by io.github.chaosawakens.mixins.LivingEntityMixin with priority 1000 [PREINJECT Applicator Phase -> expandability.mixins.json:swimming.LivingEntityMixin -> Prepare Injections ->  -> redirect$zjg001$setInWater(Lnet/minecraft/entity/LivingEntity;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/LivingEntity::setInWater with priority 1000 cannot inject into net/minecraft/entity/LivingEntity::func_213352_e(Lnet/minecraft/util/math/vector/Vector3d;)V merged by io.github.chaosawakens.mixins.LivingEntityMixin with priority 1000 [PREINJECT Applicator Phase -> expandability.mixins.json:swimming.LivingEntityMixin -> Prepare Injections ->  -> redirect$zjg001$setInWater(Lnet/minecraft/entity/LivingEntity;)Z -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30) [?:?]
	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12) [?:?]
	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$661/634366662.get(Unknown Source) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89) [?:?]
	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$669/445805369.accept(Unknown Source) [?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) [?:1.8.0_51]
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) [?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) [?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) [?:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) [?:?]
	at net.minecraft.client.main.Main$$Lambda$607/605472344.run(Unknown Source) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$494/2040452328.call(Unknown Source)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:32:08] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$661/634366662.get(Unknown Source)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$669/445805369.accept(Unknown Source)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$607/605472344.run(Unknown Source)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:32:08] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [expandability.mixins.json:swimming.LivingEntityMixin] from phase [DEFAULT] in config [expandability.mixins.json] FAILED during APPLY
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 28 more
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/entity/LivingEntity::setInWater with priority 1000 cannot inject into net/minecraft/entity/LivingEntity::func_213352_e(Lnet/minecraft/util/math/vector/Vector3d;)V merged by io.github.chaosawakens.mixins.LivingEntityMixin with priority 1000 [PREINJECT Applicator Phase -> expandability.mixins.json:swimming.LivingEntityMixin -> Prepare Injections ->  -> redirect$zjg001$setInWater(Lnet/minecraft/entity/LivingEntity;)Z -> Prepare]
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[21:32:08] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 28 more

Mod List:
Chaos Awakens 0.11.0.1
Architectury API
AttributeFix
Atum 2
AzureDoom's Chunk Loader
Baubley Heart Canisters
Blood Magic
Blueprint
Chaos Additions
Collective
CraftTweaker
Create
Curios API
Dismount Entity
DustW's Better Structure Block
ExpandAbility
Flywheel
FTB Library
FTB Quests
FTB Teams
GeckoLib
Halogen
Item Filters
JEITweaker
Just Enough Resources
JER integration
Just Enough Items
Lazy DataFixerUpper
Mantle
Mob Grinding Utils
Mob Sunscreens
Mod Name Tooltip
Mowzie's Mobs
Nameless Trinkets
No Tree Punching
Patchouli
Pure Chaos
Quests Additions
Savage Ender Dragon
Shutup Experimental Settings
Soul Trap
spark
Spice of Life: Carrot Edition
The Endergetic Expansion
Twilight Forest
Totally Harmonious Item Stages
Xaero Arrow Fix
Xaero's Minimap
Xaero's World Map

**Comment by PhweeDev** [comment]
You have ExpandAbility. That mod is not compatible with CA right now. It will be fixed in an update soon.

**Comment by Qawtykit** [comment]
Thanks!
